# Generated by Django 4.0.5 on 2023-07-19 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_refreshtoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refreshtoken',
            old_name='user_id',
            new_name='user',
        ),
    ]
